default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    config = JSON.parse(File.read("fastlane/fastlane_config.json"))
    api_key = config["api_key"]

    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(
      api_key: api_key
    )
  end
end