default_platform(:android)

platform :android do
  desc "Push a new beta build to the Play Store"
  lane :beta do
    config = JSON.parse(File.read("fastlane/fastlane_config.json"))
    json_key_file = config["json_key_file"]
    package_name = config["package_name"]

    build_app(
      task: "assembleRelease"
    )
    upload_to_play_store(
      track: 'beta',
      json_key: json_key_file,
      package_name: package_name,
    )
  end
end